server:
    port: 8081
spring:
    application:
        name: ticket
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/ticket
        username: szymonj
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false
        open-in-view: false
