spring:
    application:
        name: cloud-gateway
    main:
        web-application-type: reactive
        allow-bean-definition-overriding: true
    cloud:
        gateway:
            routes:
                -   id: event
                    uri: lb://EVENT
                    predicates:
                        - Path=/api/v1/event/**
                    filters: AuthenticationFilter

                -   id: seat
                    uri: lb://SEAT
                    predicates:
                        - Path=/api/v1/seat/**
                    filters: AuthenticationFilter

                -   id: ticket
                    uri: lb://TICKET
                    predicates:
                        - Path=/api/v1/ticket/**
                    filters: AuthenticationFilter

                -   id: sms-notification
                    uri: lb://SMS-NOTIFICATION
                    predicates:
                        - Path=/api/v1/sms-notification/**
                    filters: AuthenticationFilter

                -   id: auth-user
                    uri: lb://AUTH-USER
                    predicates:
                        - Path=/api/v1/auth-user/**

                -   id: firebase
                    uri: lb://FIREBASE
                    predicates:
                        - Path=/api/v1/firebase/**
                    filters: AuthenticationFilter

                -   id: pdf
                    uri: lb://PDF
                    predicates:
                        - Path=/api/v1/pdf/**
                    filters: AuthenticationFilter
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"
server:
    port: 8080
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER}
        fetch-registry: true
        register-with-eureka: true
