server:
    port: 8081
    error:
        include-exception: true
        include-binding-errors: always
        include-message: always
spring:
    application:
        name: event
    datasource:
        password: ${DB_PASSWORD_EVENT}
        url: ${DB_URL_EVENT}
        username: ${DB_USERNAME_EVENT}
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false
        open-in-view: false
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER}
        fetch-registry: true
        register-with-eureka: true
