server:
    port: 8088
spring:
    application:
        name: email-notification
    kafka:
        bootstrap-servers: localhost:9092
        consumer.value-deserializer: com.eve.ticketing.app.emailnotification.kafka.KafkaEmailDeserializer
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER}
        fetch-registry: true
        register-with-eureka: true
