server:
    port: 8084
spring:
    application:
        name: sms-notification
    datasource:
        password: ${DB_PASSWORD_SMS_NOTIFICATION}
        url: ${DB_URL_SMS_NOTIFICATION}
        username: ${DB_USERNAME_SMS_NOTIFICATION}
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false
        open-in-view: false
    kafka:
        bootstrap-servers: localhost:9092
        consumer.value-deserializer: com.eve.ticketing.app.smsnotification.kafka.KafkaNotificationDeserializer
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER}
        fetch-registry: true
        register-with-eureka: true
twilio:
    account_sid: ${TWILIO_ACCOUNT_SID}
    auth_token: ${TWILIO_AUTH_TOKEN}
    trial_number: ${TWILIO_TRIAL_NUMBER}
