server:
    port: 8082
spring:
    application:
        name: seat
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/seat
        username: szymonj
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false
        open-in-view: false
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
