server:
    port: 8082
spring:
    application:
        name: seat
    datasource:
        password: ${DB_PASSWORD_SEAT}
        url: ${DB_URL_SMS_SEAT}
        username: ${DB_USERNAME_SEAT}
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false
        open-in-view: false
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER}
        fetch-registry: true
        register-with-eureka: true
