server:
    port: 8087
spring:
    application:
        name: pdf
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER}
        fetch-registry: true
        register-with-eureka: true
